name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Mkdir dist
      run: mkdir dist

    - name: Build (with Clang)
      run: cl /O2 D:/a/CombineRoms/CombineRoms/combine_roms.c -o D:/a/CombineRoms/CombineRoms/combine_roms.exe

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CombineRoms-win32
        path: dist/
